name: HumineShop
main: humine.main.MainShop
version: 3.0
author: MizakiGaming
api-version: 1.13
commands:
  shop:
    usage:
    description: ouvrir le shop
    permission:
  money:
    usage:
    description:
    permission:
  ccp:
    usage:
    description:
    permission:
  chelp:
    usage:
    description:
    permission:
  tccp:
    usage:
    description:
    permission:
  rc:
    usage:
    description:
    permission:
  ccmh:
    usage:
    description:
    permission:
  tccmh:
    usage:
    description:
    permission:
  store:
    usage:
    description:
    permission:
  storedelete:
    usage:
    description:
    permission:
  ccch:
    usage:
    description:
    permission:
  tccch:
    usage:
    description:
    permission: