name: HumineShop
main: humine.main.MainShop
version: 1.2
author: MizakiGaming
api-version: 1.13
commands:
  shop:
    usage:
    description: ouvrir le shop
    permission:
  money:
    usage:
    description:
    permission:
  ccp:
    usage:
    description:
    permission:
  chelp:
    usage:
    description:
    permission:
  