name: HumineShop
main: com.humine.main.ShopMain
author: MizakiGaming
version: 1.0a
api-version: 1.13
commands:
  gemme:
    description: Voir le nombre de gemme
  shop:
    description: ouvre la boutique de cosmetique
