name: HumineShop
main: humine.main.MainShop
version: 3.0
author: MizakiGaming
api-version: 1.14
commands:
  shop:
    usage:
    description: ouvrir le shop
    permission:
  money:
    usage:
    description: voir ses humis/pixel
    permission:
  ccp:
    usage:
    description: creer un cosmetique de particule
    permission:
  chelp:
    usage:
    description: voir la liste des Material ou Particle
    permission:
  tccp:
    usage:
    description: creer un cosmetique de particule temporaire
    permission:
  rc:
    usage:
    description: supprimer un cosmetique
    permission:
  ccmh:
    usage:
    description: creer un cosmetique de Material Hat
    permission:
  tccmh:
    usage:
    description: creer un cosmetique de Material Hat temporaire
    permission:
  store:
    usage:
    description: ajouter des humis/pixel a un joueur
    permission:
  storedelete:
    usage:
    description: supprimer des humis/pixel a un joueur
    permission:
  ccch:
    usage:
    description: creer un cosmetique de Custom Head
    permission:
  tccch:
    usage:
    description: creer un cosmetique de Custom Head temporaire
    permission:
  cosmetiquecommand:
    usage:
    description: creer un cosmetique de Custom Head temporaire
    permission: